server:
  port: 0
spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://120.55.48.118:3306/user_center
    hikari:
      username: root
      password: 971229
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 120.55.48.118:8848
#        namespace: 042d49e9-38bc-48e6-974f-7b8c3567ae31

      # 元数据
#        metadata:
#          instance: yj
#          hello: world
#          version: 1.0
