server:
  port: 8888
spring:
#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: content-center

  cloud:
    nacos:
      discovery:
#        server-addr: 120.55.48.118:8848
        server-addr: localhost:8848
    #        namespace: 042d49e9-38bc-48e6-974f-7b8c3567ae31
    sentinel:
      transport:
        #        dashboard: 120.55.48.118:8080
        dashboard: localhost:8080

  datasource:
    url: jdbc:mysql://120.55.48.118:3306/content_center?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    hikari:
      username: root
      password: 971229
      driver-class-name: com.mysql.cj.jdbc.Driver

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients: user-center

# Spring Boot 监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
rocketmq:
  name-server: 120.55.48.118:9876
  producer:
    group: test-group

jwt:
  secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  # 有效期，单位秒，默认2周
  exprice-time-in-second: 1209600

    #feign:
    #  client:
    #    config:
    #      # 全局配置
    #      default:
    #        loggerLevel: full
    #  httpclient:
    #    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    #    enabled: true
    #    # feign的最大连接数
    #    max-connections: 200
    #    # feign单个路径的最大连接数
    #    max-connections-per-route: 50

